#!/usr/bin/env node

"use strict";

var path = require('path');
var debug = require('debug')('payneteasy:server');
var http = require('http');

// Глобальные костанты
global.__cfgDir = path.join(__dirname, '../', 'cfg') + path.sep;
global.__cfg = path.join(global.__cfgDir, 'cfg');
global.__initCfg = path.join(global.__cfgDir, 'initCfg');
global.__modulesCustom = path.join(__dirname, '../', 'node_modules_custom') + path.sep;
global.__pne = path.join(__dirname, 'pne') + path.sep;
global.__dao = path.join(__dirname, 'dao') + path.sep;
global.__util = path.join(__dirname, 'util') + path.sep;


require(__initCfg).then(
    //createServer,

    // DEBUG START
    function(){
        var reqData = {

        // Перевод

            endpointid: 815,
            // Transaction UUID (Пользовательский идентификатор заказа.) (128/String)
            transactionUuid: '522a5e84-3193-41d1-9d7b-5921a1c20a8d', /* DATA REQUIRED */
            // id транзакции у PayNetEasy. Появится после preauthRequest
            pneId: '20769680',
            // Сумма перевода (целевой платеж). Копейки от рублей отделяются точкой. Например 10.5 (10/Numeric)
            amount: 1, /* DATA REQUIRED */
            // Сумма которую ПО зажимает себе. Копейки от рублей отделяются точкой. Например 10.5 (10/Numeric)
            comission: 0.5, /* DATA REQUIRED */
            // НДС (сумма) (10/Numeric)
            //NDS: 0,
            // Трехзначный код валюты платежа, например RUB (3/String)
            currency: 'RUB',
            // Назначение платежа (125/String)
            'order_desc': 'order_desc!', /* DATA REQUIRED */

        // Плательщик

            // Customer’s first name (50/String)
            //payer_first_name: '',
            // Customer’s last name (50/String)
            //payer_last_name: '',
            // Customer’s date of birth, in the format YYYYMMDD. (6/Numeric)
            //payer_birthday: '',
            // Last four digits of the customer’s social security number. (4/Numeric)
            //payer_ssn: '',
            // E-mail плательщика (128/String)
            payer_email: 'email@mail.ru', /* DATA REQUIRED */
            // Телефон плательщика (15/String)
            //payer_phone: '',
            // Полный телефон плательщика, вместе с кодом города (15/String)
            //payer_cell_phone: '',
            // Код страны плательщика (2/String)
            payer_country: 'RU', /* DEFAULT */
            // Customer’s state (two-letter US state code). Please see Appendix A for a list of valid US state codes. Not applicable outside the US. (2/String)
            //payer_state: '',
            // Город плательщика (50/String)
            payer_city: 'city', /* DATA REQUIRED */
            // Почтовый индекс плательщика (10/String)
            payer_zip_code: '000000', /* DATA REQUIRED */
            // (50/String)
            payer_address1: 'address1!', /* DATA REQUIRED */
            // IP адрес плательщика (20/String)
            payer_ipaddress: '127.0.0.0', /* DATA REQUIRED */

        // Остальное

            // URL the cardholder will be redirected to upon completion of the transaction. Please note that the cardholder will be redirected in any case, no matter whether the transaction is approved or declined. (128/String)
            redirect_url: 'http://ya.ru' /* DATA REQUIRED */
            // URL the original sale is made from. (128/String)
            //site_url: ''
            // URL the transaction result will be sent to. Merchant may use this URL for custom processing of the transaction completion, e.g. to collect sales data in Merchant’s database. See more details at Merchant Callbacks (128/String)
            //server_callback_url: ''
        };



        //var req = require(__pne + 'preauthReq');
        var req = require(__pne + 'preauthStatusReq');
        req(reqData)
            .then(
                function(data){
                    console.log('data');
                    console.log(data);
                },
                function(err){
                    console.log('err');
                    console.log(err);
                }
            );
    },
    // DEBUG END
    function (err) {
        if (err instanceof Error) {
            console.error(err.stack);
        } else {
            console.error(err);
        }
    }
);

function createServer () {
    var app = require('./app');

    var port = normalizePort(process.env.PORT || '3000');
    app.set('port', port);

    var server = http.createServer(app);

    server.listen(port);
    server.on('error', onError);
    server.on('listening', onListening);

    function onError(error) {
        if (error.syscall !== 'listen') {
            throw error;
        }

        var bind = typeof port === 'string'
            ? 'Pipe ' + port
            : 'Port ' + port;

        switch (error.code) {
            case 'EACCES':
                console.error(bind + ' requires elevated privileges');
                process.exit(1);
                break;
            case 'EADDRINUSE':
                console.error(bind + ' is already in use');
                process.exit(1);
                break;
            default:
                throw error;
        }
    }

    function onListening() {
        var addr = server.address();
        var bind = typeof addr === 'string'
            ? 'pipe ' + addr
            : 'port ' + addr.port;
        debug('Listening on ' + bind);
    }
}

function normalizePort(val) {
    var port = parseInt(val, 10);

    if (isNaN(port)) {
        // named pipe
        return val;
    }

    if (port >= 0) {
        return port;
    }

    return false;
}